/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Ryan' at '6/11/16 8:59 PM' with Gradle 2.13
 *
 * @author Ryan, @date 6/11/16 8:59 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
